### ISSUE TITLE
Facing issue in Android Side only When APP is in Foreground State

### ISSUE THREAD

**Issue by RanaMusab** [RodrigoSMarques/flutter_branch_sdk#141]
when App is in Foreground State in Android Side it does not open my new Password reset Screen while in IOS its working perfect
here is my Code

`        streamSubscription =
            FlutterBranchSdk.initSession().listen((data) async {
          if (data.containsKey("+clicked_branch_link") &&
              data.containsKey("token") &&
              data["+clicked_branch_link"] == true) {
            if (data["token"] != null && data["token"] != '') {
              Get.to(ChangePassword(
                token: data["token"],
                userId: data["user_id"].toStringAsFixed(0),
                isDeepLink: true,
              ));
            }
          }
        }, onError: (error) {
          PlatformException platformException = error as PlatformException;
          print(
              'InitSession error: ${platformException.code} - ${platformException.message}');
        });`

**Comment by RodrigoSMarques** [comment]
I didn't understand the problem.

Have you verified that the data is being returned correctly?

It just doesn't open the screen?

More details.

Please do not remove the template as it is important to understand and reproduce the problem.

--

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Flutter: version: [e.g. 2.2.3]
 - Package version: [e.g. 3.3.0]
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Flutter: version: [e.g. 2.2.3]
 - Package version: [e.g. 3.3.0]
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]

**Additional context**
Add any other context about the problem here.

**Comment by RanaMusab** [comment]
No the issue is solved
the issue was with in android manifest file
