### ISSUE TITLE
Branch generates very long links when adding custom params

### ISSUE THREAD

**Issue by mtalha101** [RodrigoSMarques/flutter_branch_sdk#280]
**Describe the bug**
When I add custom parameters to link properties while generating a short link, I receive a very large link like: `https://app.evershop.ai/a/key_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?%24randomized_bundle_token=1253323032068742588&tags=influencer&alias=u/testuser7140&channel=influencer&feature=influencer&source=ios&data=eyIkbG9jYWxseV9pbmRleGFibGUiOnRydWUsIiRvZ190aXRsZSI6IkV2ZXJTaG9wIEluZmx1ZW5jZXIiLCIka2V5d29yZHMiOlsiaW5mbHVlbmNlciJdLCIkcHVibGljbHlfaW5kZXhhYmxlIjp0cnVlLCIkY2Fub25pY2FsX3VybCI6Imh0dHBzOi8vd2ViLmV2ZXJzaG9wLmFpL3UvdGVzdHVzZXI3MTQwIiwiJGNhbm9uaWNhbF9pZGVudGlmaWVyIjoiZXZlcnNob3AvaW5mbHVlbmNlciJ9`. This started happening when I added custom params i.e. `$android_url` and `$ios_url`, to redirect the user to webpage if the app is not installed

**To Reproduce**
This is my link generating code:
```
return await FlutterBranchSdk.getShortUrl(
        buo: BranchUniversalObject(
          canonicalIdentifier: 'evershop/post',
          canonicalUrl: 'https://web.evershop.ai/p/$id',
          title: 'EverShop Post',
          keywords: ['post'],
        ),
        linkProperties: BranchLinkProperties(
          tags: ['post'],
          campaign: 'post',
          feature: 'post',
          channel: 'post',
          alias: 'p/$id',
        )
          ..addControlParam('\$uri_redirect_mode', '1')
          ..addControlParam('\$ios_url', 'https://web.evershop.ai/p/$id')
          ..addControlParam('\$android_url', 'https://web.evershop.ai/p/$id'),
      );
```

**Expected behavior**
The sdk should generate a link like `https://app.evershop.ai/u/testuser7140` which should be redirected to webapge `https://web.evershop.ai/u/testuser7140` if the app is not installed.

**Smartphone:**
 - Flutter: version: 3.16.4
 - Package version: ^6.6.0
 - OS: iOS 16.4
 - Device: iPhone Xs
 
**Web:**
 - Flutter: version: 3.16.4
 - Package version: ^6.6.0
 - OS: Mac
 - Browser Chrome
 - Version 120.0.6099.199

**Comment by RodrigoSMarques** [comment]
Based on the tests I carried out (including in a native Swift project to ensure that the problem was not in the Flutter plugin), the problem does not occur when using the `$android_url` and `$ios_url` parameters, but when combining the `alias` parameter.

If you remove the `alias, a short link is generated.

This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter package, but in the Native SDK.

Please open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)


<img width="1281" alt="Captura de Tela 2024-01-11 às 10 11 03" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/17687286/ef069597-d7ef-457f-ae05-4db9c40b91b2">
<img width="1281" alt="Captura de Tela 2024-01-11 às 10 08 27" src="https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/17687286/143f416c-a04e-469b-88c2-0621eea525a0">

**Comment by mtalha101** [comment]
Thank you so much Sir! I will open an issue for iOS Native SDK
