### ISSUE TITLE
Not able to see  via Facebook  installs in branch dashboard

### ISSUE THREAD

**Issue by RAFI-006** [RodrigoSMarques/flutter_branch_sdk#285]
**Please check the below link for issue reference**
[stack overflow link](https://stackoverflow.com/questions/49955368/branch-io-deep-linked-url-not-passing-data-in-app-from-facebook-adsl)

what is the alternate I can use for this below code from this package ,not able to see any other similar function 

**enableFacebookAppLinkCheck()**

Any help is highly appreciated 
I am using the current package version -  flutter_branch_sdk: ^7.0.2

**Comment by RodrigoSMarques** [comment]
These methods have been deprecated by Branch in the native SDKs in the versions below:

Because they are deprecated in the native SDK, they were removed from the flutter plugin.

If you need a solution, you need to contact Branch support. [link](https://help.branch.io/using-branch/page/submit-a-ticket)

- [https://github.com/BranchMetrics/android-branch-deep-linking-attribution/releases/tag/5.7.0](https://github.com/BranchMetrics/android-branch-deep-linking-attribution/releases/tag/5.7.0)

- [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/releases/tag/3.0.0](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/releases/tag/3.0.0)
