### ISSUE TITLE
SDK doesn't handle existing path correctly

### ISSUE THREAD

**Issue by vasito95** [RodrigoSMarques/flutter_branch_sdk#381]
**Describe the bug**
Not getting proper error handling when creating a link with the path that already exist.

**To Reproduce**
1. Create link
2. Try creating another one with the same path
 
**Web:**
 - Flutter: version: [e.g. 3.24.3]
 - flutter_branch_sdk version: [e.g. 8.1.0]
 - OS: [e.g. Mac]
 - Browser [e.g. chrome]
 
 - **Additional context**

Console log:
`DartError: TypeError: Instance of 'NativeError': type 'NativeError' is not a subtype of type 'String?'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
errors.dart:296
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1405:3                              _failedAsCheck
rti.dart:1405
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1395:3                              _generalNullableAsCheckImplementation
rti.dart:1395
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 243:33  _argumentErrors
operations.dart:243
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 438:22  validateFunctionToJSArgs
operations.dart:438
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 198:24    _callDartFunctionFast2
js_allow_interop_patch.dart:198
https://cdn.branch.io/branch-latest.min.js 132:325                                g
https://cdn.branch.io/branch-latest.min.js 151:129                                <fn>
https://cdn.branch.io/branch-latest.min.js 136:26                                 <fn>
https://cdn.branch.io/branch-latest.min.js 68:270                                 m
https://cdn.branch.io/branch-latest.min.js 67:196                                 onreadystatechange`

Network response:

`{
    "error": {
        "code": 400,
        "message": "Link alias conflict: thebocaratonresort.app.link/test_test_test"
    }
}`

**Comment by RodrigoSMarques** [comment]
@vasito95 

The reported error is occurring in the Branch Native SDK, in the Javascript layer.

Since the error occurs in the Javascript layer of the SDK, I cannot recover the error and handle it in Dart.

The error occurs on line 67 of the **branch-latest.min.js** file.

The issue must be opened in the Branch repository of the [Javascript SDK](https://github.com/BranchMetrics/web-branch-deep-linking-attribution).

<img width="1690" alt="Captura de Tela 2024-09-21 às 15 58 04" src="https://github.com/user-attachments/assets/6cd1e0c6-6f30-41aa-bf86-1752fc1620a6">

<img width="1690" alt="Captura de Tela 2024-09-21 às 15 59 22" src="https://github.com/user-attachments/assets/e2512cd7-653d-4d60-a3ae-512b00ac9774">
