### ISSUE TITLE
Logs & events issue

### ISSUE THREAD

**Issue by osama450** [RodrigoSMarques/flutter_branch_sdk#388]
**Describe the bug**
Hi there, I need to send logs or event for user actions I'm using this code to send this data 
I'm using the free plan , thanks

**Expected behavior**
this my code , and I don't get any data in dashboard and i don't know where should will be 
`  Future<void> logToBranchIo(
      {required String name, Map<String, dynamic>? parameters}) async {
    BranchEvent eventCustom =
        BranchEvent.standardEvent(BranchStandardEvent.LOGIN);
    FlutterBranchSdk.trackContentWithoutBuo(branchEvent: eventCustom);
  }.`
  and this 
  `  Future<void> logToBranchIo(
      {required String name, Map<String, dynamic>? parameters}) async {
    BranchEvent eventCustom =
        BranchEvent.customEvent('Test');
    FlutterBranchSdk.trackContentWithoutBuo(branchEvent: eventCustom);
  }`

**Mobile (Please complete the following information. remove session if not Mobile):**
 - Flutter: version:  last version
 - flutter_branch_sdk version: last version
 - OS:  IOS 16
 - Device: iPhone16

**Comment by RodrigoSMarques** [comment]
I found some events in the Liveview option.

But I advise you to open a support ticket to Branch, since this is not a question about the Flutter plugin, but about Branch services.

Branch Support: (https://help.branch.io/using-branch/page/submit-a-ticket)

They will be able to guide you better.

<img width="1706" alt="image" src="https://github.com/user-attachments/assets/bef6c03b-d55f-49d9-91e9-4f354c87cd3f">

**Comment by osama450** [comment]
This events from my account ?

**Comment by RodrigoSMarques** [comment]
No. These are my events.

I am not Branch support, I do not have access to their events.

**Comment by RodrigoSMarques** [comment]
Closed. If necessary open again.
