### ISSUE TITLE
validateSDKIntegration not working on iOS

### ISSUE THREAD

**Issue by ajain-bst** [RodrigoSMarques/flutter_branch_sdk#57]
I get a native iOS alert saying "The network request was invalid" on calling `FlutterBranchSdk.validateSDKIntegration()`.
It is working fine on Android though.

flutter_branch_sdk: ^1.2.0
flutter 1.20.4
iOS 13.6

**Comment by RodrigoSMarques** [comment]
Hi @ajain-bst 
I never saw this error message. This is related to the Branch SDK.
I did a search and found several references on Google, but I didn't identify a solution.

[https://www.google.com/search?rls=en&q=branch+sdk+The+network+request+was+invalid&ie=UTF-8&oe=UTF-8](https://www.google.com/search?rls=en&q=branch+sdk+The+network+request+was+invalid&ie=UTF-8&oe=UTF-8)

Try to delete the application from the device and install again, otherwise I believe you will have to open a ticket with Branch.

**Comment by ajain-bst** [comment]
it seems to have been fixed on its own. Closing.
