### ISSUE TITLE
How can I get full URI link clicked

### ISSUE THREAD

**Issue by vukhacbiet** [RodrigoSMarques/flutter_branch_sdk#67]
I want to handle URI path (ex: myuri://path/to/somewhere) to process route in my app.

But when test which URI, allthing i received is `{+clicked_branch_link: false, +is_first_session: false}`
 and not have any data.

Please tell me how can I receive full URI link when I clicked.

**Comment by RodrigoSMarques** [comment]
@vukhacbiet 

You are receiving this return without data, because the URI was not created by the Branch (FlutterBranchSdk.getShortUrl or FlutterBranchSdk.showShareSheet methods).
You are creating your own route, manually.

In this case, you need another package, not Branch:

https://pub.dev/packages/uni_links
